apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "myapp.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: service-1
            port:
              number: 80
      - path: "/service-2"
        pathType: Prefix
        backend:
          service:
            name: service-2
            port:
              number: 80
      - path: "/service-3"
        pathType: Prefix
        backend:
          service:
            name: service-3
            port:
              number: 80