name: Publish Docker image to Github Packages
on:
    push:
        branches:
            - main
        paths:
            - "**/**"

permissions:
    contents: read
    packages: write

jobs:
    Service1:
        runs-on: ubuntu-latest
        name: Build and Push Docker image to Github Packages
        steps:
            - name: Check out repo
              uses: actions/checkout@v4
              path: Service-1
            - name: Login to GitHub registry
              uses: docker/login-action@v3
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io

            - name: Build and Push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  pull: true
                  tags: |
                        docker.pkg.github.com/interviewandhealth/k8s-test/service-1
                        ghcr.io/interviewandhealth/k8s-test/service-1

    Service2:
        runs-on: ubuntu-latest
        name: Build and Push Docker image to Github Packages
        steps:
            - name: Check out repo
              uses: actions/checkout@v4
              path: Service-2
            - name: Login to GitHub registry
              uses: docker/login-action@v3
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io

            - name: Build and Push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  pull: true
                  tags: |
                        docker.pkg.github.com/interviewandhealth/k8s-test/service-2
                        ghcr.io/interviewandhealth/k8s-test/service-2

    Service3:
        runs-on: ubuntu-latest
        name: Build and Push Docker image to Github Packages
        steps:
            - name: Check out repo
              uses: actions/checkout@v4
              path: Service-3
            - name: Login to GitHub registry
              uses: docker/login-action@v3
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io

            - name: Build and Push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  pull: true
                  tags: |
                        docker.pkg.github.com/interviewandhealth/k8s-test/service-3
                        ghcr.io/interviewandhealth/k8s-test/service-3